name: Generate Checksum on Push to Main(Vtt to Ass) # 工作流程名稱

# 觸發條件：當程式碼被推送到 main 分支，且 vtt_to_ass_converter.py 檔案發生變更時
on:
  push:
    branches: [ main ]        # 只監聽 main 分支
    paths:
      - 'vtt_to_ass_converter.py' # 只在 vtt_to_ass_converter.py 變更時觸發

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 環境中運行

    steps:
      # 步驟 1：簽出儲存庫程式碼
      # 這會將你的儲存庫內容下載到 Action 運行的虛擬環境中
      - name: Checkout code
        uses: actions/checkout@v4 # 使用最新版本的 checkout action

        # 步驟 2：生成 SHA256 校驗和檔案 (只包含校驗和值)
      - name: Generate SHA256 Checksum
        run: |
          sha256sum vtt_to_ass_converter.py | awk '{print $1}' > vtt_to_ass_converter.py.sha256
          echo "Checksum generated (value only):"
          cat vtt_to_ass_converter.py.sha256

      # 步驟 3：配置 Git 並提交校驗和檔案
      # 這個步驟會將新生成或更新的校驗和檔案提交回你的儲存庫
      - name: Commit checksum file
        run: |
          # 配置 Git 使用者資訊，這樣提交才會有作者
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" # GitHub Actions bot 的郵箱
          git config --local user.name "github-actions[bot]" # GitHub Actions bot 的名稱

          # 將生成的校驗和檔案添加到 Git 暫存區
          git add vtt_to_ass_converter.py.sha256

          # 檢查是否有實際的變更被暫存（避免空的提交）
          # 如果校驗和檔案內容沒有變化，就不執行提交
          if git diff --staged --quiet; then
            echo "No changes to the checksum file to commit."
          else
            # 如果有變更，則執行提交
            git commit -m "Automated: Update checksum for vtt_to_ass_converter.py" # 自動提交的訊息
            echo "Checksum file committed."
          fi

      # 步驟 4：將提交推送到遠程儲存庫
      # 使用一個可靠的 Action 將本地的提交推送到 GitHub 上的 main 分支
      - name: Push changes
        uses: ad-m/github-push-action@master # 一個常用的推送 Action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自動提供的權杖進行認證
          branch: main # 明確指定推送到 main 分支
          # 只有在上一步有實際提交時才推送 (可選，但建議)
          # 你也可以移除這個 if，讓它總是嘗試推送，但如果沒有 commit，它也不會做任何事
          if: steps.commit.outputs.committed == 'true' # 依賴上一步 commit action 的輸出 (如果有的話)
                                                        ad-m/github-push-action 會自動處理無 commit 的情況
