name: Create and Sign Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare and Sign Release Script
        id: prepare_script
        run: |
          # 1. 準備用於簽署的內容 (固定區塊模式)
          echo "Preparing data for signing using fixed code block..."
          # 找到 "main()" 函數的起始行號
          MAIN_FUNC_START_LINE=$(grep -n -m 1 "^main()" media_processor.sh | cut -d: -f1)
          if [ -z "$MAIN_FUNC_START_LINE" ]; then
            echo "::error::Could not find main() anchor in script!"
            exit 1
          fi
          # 提取從檔案開頭到 main() 函數之前的所有行作為簽署內容
          head -n $((MAIN_FUNC_START_LINE - 1)) media_processor.sh | sed 's/\r$//' > data_to_sign.sh

          # 2. 對這個準備好的、純淨的內容產生數位簽章
          echo "Generating signature for the prepared data..."
          gpg --detach-sign --armor -u ${{ secrets.GPG_SIGNING_KEY_ID }} data_to_sign.sh
          SIGNATURE_B64=$(cat data_to_sign.sh.asc | base64 -w 0)
          
          # 3. 準備最終要發布的腳本
          echo "Preparing the final release script..."
          cp media_processor.sh release_script.sh
          
          # 4. 將所有動態值注入到最終腳本中
          PUBLIC_KEY_B64=$(gpg --armor --export ${{ secrets.GPG_SIGNING_KEY_ID }} | base64 -w 0)
          sed -i "s/^SCRIPT_VERSION=\".*\"/SCRIPT_VERSION=\"${{ github.ref_name }}\"/" release_script.sh
          sed -i "s/^SCRIPT_UPDATE_DATE=\".*\"/SCRIPT_UPDATE_DATE=\"$(date +%Y-%m-%d)\"/" release_script.sh
          sed -i "s@PUBLIC_KEY_PLACEHOLDER@${PUBLIC_KEY_B64}@" release_script.sh
          sed -i "s@SIGNATURE_PLACEHOLDER@${SIGNATURE_B64}@" release_script.sh
          
          echo "script_path=release_script.sh" >> $GITHUB_OUTPUT

      - name: Create Release Package
        run: |
          mv ${{ steps.prepare_script.outputs.script_path }} media_processor.sh
          zip release.zip media_processor.sh estimate_size.py sync_helper.py LICENSE README.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            自動化發布版本 ${{ github.ref_name }}。
            此版本包含 GPG 數位簽章，可透過腳本內建的「腳本完整性驗證」功能進行驗證。
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
